name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ['self-hosted', 'linux', 'x64', 'discord']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      #- name: Install dependencies
      #  run: npm ci
      #  working-directory: ./ 

      #- name: Build Next App
      #  run: npm run build
      #  working-directory: ./

      - name: Run Next App
        run: |
          pm2 startOrRestart ecosystem.config.js --env production
        working-directory: ./
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}