name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ["self-hosted", "linux", "X64"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "18.16.0"

      - name: Install dependencies
        run: yarn
        working-directory: ./

      - name: Update Config File
        run: mv src/config/config-server.json src/config/config.json
        working-directory: ./

      - name: Run Discord Bot
        run: |
          nvm use 18
          pm2 startOrRestart ecosystem.config.cjs --env production
        working-directory: ./
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
