name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ["self-hosted", "linux", "X64", "discord"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn
        working-directory: ./

      - name: Run Discord Bot
        run: |
          pm2 startOrRestart ecosystem.config.js --env production
        working-directory: ./
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
